### ISSUE TITLE
view_user page - there's nothing here

### ISSUE THREAD

**Issue by pikachurus** [mantisbt-plugins/Userdata#1]
Hi!

mantisbt 2.26
nginx 1.25
php 7.4.33

Installed this plugin:
![image](https://github.com/mantisbt-plugins/Userdata/assets/16227309/ddb0ef16-8335-44ab-b98b-e4f4403978bd)

make some fields:
![image](https://github.com/mantisbt-plugins/Userdata/assets/16227309/1651aac8-243c-4c76-a5a6-3bc77a1dc284)

and userdata:
![image](https://github.com/mantisbt-plugins/Userdata/assets/16227309/1ee3eea4-7474-4fff-a150-465c678b5d83)

and view_user_page:
![image](https://github.com/mantisbt-plugins/Userdata/assets/16227309/924b152e-3edc-4e6c-bf46-882248c9b007)

at account_page i can see Custom Fields tab:
![image](https://github.com/mantisbt-plugins/Userdata/assets/16227309/3a20d4c0-17fc-45c0-8e1f-ac616c42e2ec)

**Comment by ghost** [comment]
Please follow the instructions to enable this as statd in the install.txt :
In case you want to show the data within the view_user_page ,
please add the following lines to view_user_page.php just before "layout_page_end();
// Userdata-plugin
event_signal( 'EVENT_USER_PAGE',  $f_user_id ); 
// Userdata-plugin
