### ISSUE TITLE
Unnecessary customization of MantisBT core

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Userdata#2]
Your install instructions state that a new event `EVENT_ACCOUNT_DELETED` needs to be added in 2 places

https://github.com/mantisbt-plugins/Userdata/blob/3e8c2bf3b2ad8e5e7125c44486cf55620db4ee23/docs/install.txt#L13-L28

I do not understand this requirement.

First of all it is not good practice to trigger such back-end events in the front-end, they should be signaled from the API, in this case by the user_delete() function. 

If you actually look there, you will notice that MantisBT already defines **EVENT_MANAGE_USER_DELETE ** for this purpose (see [documentation](https://mantisbt.org/docs/master/en-US/Developers_Guide/html-desktop/#dev.eventref.manage.user)), since 1.3.0.

**Comment by ghost** [comment]
This will be adjusted in version 2.20
