### ISSUE TITLE
Undefined array key "public" when adding a new definition

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Userdata#3]
SYSTEM WARNING: 'Undefined array key "public"' in '.../userdata/pages/definition_action_add.php' line 4

**Comment by ghost** [comment]
This one I cannot reproduce in my test environment using this error setting: $g_display_errors = array(E_ALL               => DISPLAY_ERROR_HALT,);

**Comment by dregad** [comment]
Which php version?

**Comment by ghost** [comment]
PHP 7.4.33

**Comment by dregad** [comment]
OK that's why you can't reproduce, php 8 is stricter

**Comment by ghost** [comment]
Got it, will chnage the code tio make it php8 compliant.
