### ISSUE TITLE
Error when adding new definition with empty or non-numeric value for sequence

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Userdata#4]
APPLICATION ERROR 401

Database query failed. Error received from database was #1366: Incorrect integer value: '' for column 'userdata_seq' at row 1 for the query: INSERT INTO mantis_plugin_Userdata_fields_table ( userdata_seq, userdata_name, userdata_public ) VALUES ( '','test','0' ).
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
Detailed error information

    Full path: /mnt/c/Users/Regad/Documents/dev/mantisbt/core/classes/DbQuery.class.php
    Line number: 301

**Comment by ghost** [comment]
Fixed in version 2.2.0
