### ISSUE TITLE
UI adjustments / improvement

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Userdata#6]
### Elements not following standard MantisBT UI.

![image](https://github.com/mantisbt-plugins/Userdata/assets/449891/f8e01299-d2d7-4fe6-ae03-b838e04cf1f7)
![image](https://github.com/mantisbt-plugins/Userdata/assets/449891/f6e2dea3-8559-4a30-83f8-aa2b43301ddc)

1. This should be a button, not a plain link (consider using print_link_button())
2. header should span all the way to the right of the section
3. Non-standard display for checkbox, CSS needs adjustment
4. Non-standard display for button, CSS needs adjustment
5. Delete and Edit actions should be buttons; suggest placing Edit first
6. Wrong styling for section footer, CSS needs adjustment

### Layout problems
- Section should be aligned to the left (you probably have an extra `<div>` somewhere
  ![image](https://github.com/mantisbt-plugins/Userdata/assets/449891/b7e189c4-5ff7-41b0-ad2c-2da6e1315274)

- In configuration page, I find it confusing to mix the list of definitions, and the form to add a new one. Suggest to move the adding to a separate section or page.

**Comment by dregad** [comment]
In view_user_page, I believe it would look nicer if the _Userdata_ section were the same width as _User Information_ section. 

With the current layout, if you are viewing a very active user, the Timeline section would be quite long, and UserData would be displayed at the bottom after a big empty space on the left, possibly even not visible on the page without scrolling.

See #8

**Comment by ghost** [comment]
Adressed in version 2.20
