### ISSUE TITLE
New Event to insert section in view_user_page.php

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Userdata#8]
Your install instructions state that a new event EVENT_USER_PAGE needs to be added in view_user_page.php.

I could consider adding the signal (possibly with a different name) in MantisBT core, to insert plugin-specific section(s) below *User Information*

I think a better location would be
https://github.com/mantisbt/mantisbt/blob/f30b8e53ec2ac420e267b8b0df41c850142db4de/view_user_page.php#L202

Taking into consideration my comment https://github.com/mantisbt-plugins/Userdata/issues/6#issuecomment-1983513456
> In view_user_page, I believe it would look nicer if the _Userdata_ section were the same width as _User Information_ section. 
> 
> With the current layout, if you are viewing a very active user, the Timeline section would be quite long, and UserData would be displayed at the bottom after a big empty space on the left, possibly even not visible on the page without scrolling.

That means adjusting the markup in showdata.php.

Related to #2

**Comment by ghost** [comment]
Even better to have a standard event, let me know if you want to use a different name for this event
As for the relocation, fully agree.

**Comment by ghost** [comment]
@dregad Any news on the new event?

**Comment by dregad** [comment]
I forgot 🤯 sorry

Would you mind opening an issue at https://mantisbt.org/bugs, referencing this ?

**Comment by ghost** [comment]
Have done that: https://mantisbt.org/bugs/view.php?id=34605
